# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9460305124d47d0c4f8eec8a32dcc464f792f0b80f80547429d36df555b431c61c9b45d823ff79fb7b1c77b003fcf9e7f5ff9d7057931feba915a9ff7542e8e6

test:
  secret_key_base: 9e781592f1403518ad6ed091bfc58db5b0c6acf308deff98bc35a8602a65c354fc440e0471450263fc2f23ee27ab33e08a28377db494c56427820eff38884eaa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
